package com.keystone.auth.infrastructure.security;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.KeyFactory;
import java.security.NoSuchAlgorithmException;
import java.security.interfaces.RSAPrivateKey;
import java.security.interfaces.RSAPublicKey;
import java.security.spec.InvalidKeySpecException;
import java.security.spec.PKCS8EncodedKeySpec;
import java.security.spec.X509EncodedKeySpec;
import java.util.Base64;
import java.util.Objects;

/**
 * RS256 key material: a {@code kid} plus the matching public/private RSA keys. Loaded from PEM
 * files generated by the {@code openssl} commands in the README.
 */
public record RsaKeyMaterial(String keyId, RSAPrivateKey privateKey, RSAPublicKey publicKey) {

  public RsaKeyMaterial {
    Objects.requireNonNull(keyId, "keyId");
    Objects.requireNonNull(privateKey, "privateKey");
    Objects.requireNonNull(publicKey, "publicKey");
    if (keyId.isBlank()) {
      throw new IllegalArgumentException("keyId must not be blank");
    }
  }

  public static RsaKeyMaterial load(String keyId, Path privateKeyPath, Path publicKeyPath) {
    try {
      var privateKey = readPrivateKey(privateKeyPath);
      var publicKey = readPublicKey(publicKeyPath);
      return new RsaKeyMaterial(keyId, privateKey, publicKey);
    } catch (IOException | NoSuchAlgorithmException | InvalidKeySpecException e) {
      throw new IllegalStateException(
          "Unable to load RSA key material from " + privateKeyPath + " / " + publicKeyPath, e);
    }
  }

  private static RSAPrivateKey readPrivateKey(Path path)
      throws IOException, NoSuchAlgorithmException, InvalidKeySpecException {
    var bytes = decodePem(Files.readString(path), "PRIVATE KEY");
    var factory = KeyFactory.getInstance("RSA");
    return (RSAPrivateKey) factory.generatePrivate(new PKCS8EncodedKeySpec(bytes));
  }

  private static RSAPublicKey readPublicKey(Path path)
      throws IOException, NoSuchAlgorithmException, InvalidKeySpecException {
    var bytes = decodePem(Files.readString(path), "PUBLIC KEY");
    var factory = KeyFactory.getInstance("RSA");
    return (RSAPublicKey) factory.generatePublic(new X509EncodedKeySpec(bytes));
  }

  private static byte[] decodePem(String pem, String label) {
    var base64 =
        pem.replace("-----BEGIN " + label + "-----", "")
            .replace("-----END " + label + "-----", "")
            .replaceAll("\\s", "");
    return Base64.getDecoder().decode(base64);
  }
}
